stages:
  - build
  - deploy

variables:
  AZURE_WEBAPP_NAME: "ppm-frontend-app"
  AZURE_RESOURCE_GROUP: "ppm-rg-dev"
  BUILD_DIR: ".next"

build:
  stage: build
  image: node
  script:
    - npm install
    - npm run build
    - ls -a
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/.next
    #expire_in: 1 week  # Adjust as needed

deploy:
  stage: deploy
  image: mcr.microsoft.com/azure-cli
  environment: production
  script:
    - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    - apk update && apk add zip
    - pwd
    - cd $CI_PROJECT_DIR
    - zip -r deploy.zip .
    - pwd
    - ls -a
    - az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_NAME --src deploy.zip
  only:
    - pipe-test-17nov 